### ISSUE TITLE
Option to only include specific metrics/tags

### ISSUE THREAD

**Issue by mlahargou** [int128/datadog-actions-metrics#1081]
We'd like to have the option to only send specific metrics with specific tags. 
Ideally, we could configure this in the yml.

Our DataDog bill has been increasing lately, and part of the reason is we are 
sending too many metrics/tags from this app. We do, however, need specific metrics
sent.

Something like this maybe?

```yml
         - name: Send metrics to Datadog
           uses: int128/datadog-actions-metrics@v1
           with:
              ...
              collect-job-metrics: true
              collect-step-metrics: true
              metrics:
                 - github.actions.workflow_run.conclusion.failure_total
                 - github.actions.workflow_run.duration_second.distribution
                 - github.actions.job.conclusion.success_total
                 - github.actions.job.conclusion.failure_total
                 - github.actions.job.queued_duration_second.distribution
                 - github.actions.job.duration_second.distribution
                 - github.actions.step.conclusion.failure_total
                 - github.actions.step.duration_second.distribution
```

As for limiting the number of tags, maybe we could key off of each metric in the sequence above and specify the tags we want sent with each?

Ref: https://github.com/int128/datadog-actions-metrics/issues/1021
