### ISSUE TITLE
No more github.actions.job.duration_second?

### ISSUE THREAD

**Issue by jduan-highnote** [int128/datadog-actions-metrics#1087]
We are using the latest version of this github action and I noticed that we stopped getting this metric `github.actions.job.duration_second`. 

Here's our workflow file:
```
jobs:
  submit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: int128/datadog-actions-metrics@v1
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_TOKEN  }}
          datadog-site: us5.datadoghq.com
          collect-job-metrics: true
          collect-step-metrics: false
          disable-distribution-metrics: true
```

Notice that we set `disable-distribution-metrics` to true because we have a lot of workflows and if we turn on disable-distribution-metrics, it will increase our Datadog cost by a lot. 

Is there a way to get back the old `github.actions.job.duration_second` metric without distribution being turned on? Thanks!
