### ISSUE TITLE
No job metrics sent

### ISSUE THREAD

**Issue by craig-cazoo** [int128/datadog-actions-metrics#516]
Hi, I recently started using this action and was able to start sending workflow metrics easily

However, I have ran into an issue when enabling `collect-job-metrics`

No job metrics are being sent to datadog and I get the following warning for my workflow:

```
Warning: Could not get the check suite: GraphqlError: Resource not accessible by integration
```

Here's my workflow:

```
name: Track deployment workflow metrics to Datadog

on:
    workflow_run:
        workflows:
            - Deploy to dev environment
            - Deploy to test environment
            - Deploy to prod environment
        types:
            - completed

jobs:
    send_metrics:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: int128/datadog-actions-metrics@v1
              with:
                  datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
                  datadog-site: datadoghq.eu
                  collect-job-metrics: true
                  github-token: ${{ secrets.GITHUB_TOKEN }}
```

Do I need to enable some permissions for my github token or have I set up my workflow incorrectly?

Many thanks

Craig
