### ISSUE TITLE
Unable to produce job metrics despite added permissions

### ISSUE THREAD

**Issue by eterhoven** [int128/datadog-actions-metrics#668]
Hi there.

I am very grateful for your action, and I am using it within a repository, as part of a workflow triggered by the completion of any other workflow in that same repository. My Datadog Metrics workflow looks as follows:

```
name: Datadog Metrics Collector

on:
  workflow_run:
    workflows: 
      - '**'
    types: 
      - completed
    branches:
      - '**'
    permissions:
      actions: read
      checks: read
      contents: read

jobs:
  send_metrics:
    runs-on: [redacted]
    timeout-minutes: 10
    steps:
      - name: Datadog metric collection
        uses: int128/datadog-actions-metrics@29ebe39408450214940f0b17dcb7d8926aea58aa #v1.48.0
        with:
          datadog-api-key: ${{ secrets.redacted }}
          datadog-site: datadoghq.eu
          collect-job-metrics: true
```

I am receiving workflow metrics, and api limit metrics, but not job metrics. Am I doing something wrong here?

Any help is really appreciated, thank you!
